# .github/workflows/test.yml

name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # No need to specify Node version here

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify Node.js 20 explicitly here

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend 

      - name: Run tests
        run: npm test
        working-directory: ./frontend

      - name: Run tests with coverage
        run: npm test -- --coverage
        env:
          CI: true
